import React from 'react'

const Review = () => {
  return (
    <div>
        <div>
            <h1 className="text-4xl sm:text-3xl font-medium mb-2 text-gray-900">Hot Review</h1>
        </div>
        <div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex enim dolorem et id molestiae nam eius autem ipsa distinctio porro amet cupiditate, aperiam sunt, tempora magni accusamus quisquam, fuga corrupti omnis repellat quae! Repudiandae, sequi optio. Molestiae quo impedit ut numquam voluptatem perferendis nesciunt harum, quam atque voluptatibus maxime quia, quidem doloremque laboriosam dolores necessitatibus. Laudantium asperiores, iure facere animi nam soluta numquam? Iusto veritatis possimus vitae officiis aliquam minus deleniti vero. Veritatis quas eligendi et repellat reprehenderit facere repudiandae omnis animi laboriosam voluptates ipsum excepturi optio alias provident, repellendus minima dignissimos aliquam illum eum veniam cupiditate, necessitatibus ipsa odio.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex enim dolorem et id molestiae nam eius autem ipsa distinctio porro amet cupiditate, aperiam sunt, tempora magni accusamus quisquam, fuga corrupti omnis repellat quae! Repudiandae, sequi optio. Molestiae quo impedit ut numquam voluptatem perferendis nesciunt harum, quam atque voluptatibus maxime quia, quidem doloremque laboriosam dolores necessitatibus. Laudantium asperiores, iure facere animi nam soluta numquam? Iusto veritatis possimus vitae officiis aliquam minus deleniti vero. Veritatis quas eligendi et repellat reprehenderit facere repudiandae omnis animi laboriosam voluptates ipsum excepturi optio alias provident, repellendus minima dignissimos aliquam illum eum veniam cupiditate, necessitatibus ipsa odio.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex enim dolorem et id molestiae nam eius autem ipsa distinctio porro amet cupiditate, aperiam sunt, tempora magni accusamus quisquam, fuga corrupti omnis repellat quae! Repudiandae, sequi optio. Molestiae quo impedit ut numquam voluptatem perferendis nesciunt harum, quam atque voluptatibus maxime quia, quidem doloremque laboriosam dolores necessitatibus. Laudantium asperiores, iure facere animi nam soluta numquam? Iusto veritatis possimus vitae officiis aliquam minus deleniti vero. Veritatis quas eligendi et repellat reprehenderit facere repudiandae omnis animi laboriosam voluptates ipsum excepturi optio alias provident, repellendus minima dignissimos aliquam illum eum veniam cupiditate, necessitatibus ipsa odio.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex enim dolorem et id molestiae nam eius autem ipsa distinctio porro amet cupiditate, aperiam sunt, tempora magni accusamus quisquam, fuga corrupti omnis repellat quae! Repudiandae, sequi optio. Molestiae quo impedit ut numquam voluptatem perferendis nesciunt harum, quam atque voluptatibus maxime quia, quidem doloremque laboriosam dolores necessitatibus. Laudantium asperiores, iure facere animi nam soluta numquam? Iusto veritatis possimus vitae officiis aliquam minus deleniti vero. Veritatis quas eligendi et repellat reprehenderit facere repudiandae omnis animi laboriosam voluptates ipsum excepturi optio alias provident, repellendus minima dignissimos aliquam illum eum veniam cupiditate, necessitatibus ipsa odio.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex enim dolorem et id molestiae nam eius autem ipsa distinctio porro amet cupiditate, aperiam sunt, tempora magni accusamus quisquam, fuga corrupti omnis repellat quae! Repudiandae, sequi optio. Molestiae quo impedit ut numquam voluptatem perferendis nesciunt harum, quam atque voluptatibus maxime quia, quidem doloremque laboriosam dolores necessitatibus. Laudantium asperiores, iure facere animi nam soluta numquam? Iusto veritatis possimus vitae officiis aliquam minus deleniti vero. Veritatis quas eligendi et repellat reprehenderit facere repudiandae omnis animi laboriosam voluptates ipsum excepturi optio alias provident, repellendus minima dignissimos aliquam illum eum veniam cupiditate, necessitatibus ipsa odio.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex enim dolorem et id molestiae nam eius autem ipsa distinctio porro amet cupiditate, aperiam sunt, tempora magni accusamus quisquam, fuga corrupti omnis repellat quae! Repudiandae, sequi optio. Molestiae quo impedit ut numquam voluptatem perferendis nesciunt harum, quam atque voluptatibus maxime quia, quidem doloremque laboriosam dolores necessitatibus. Laudantium asperiores, iure facere animi nam soluta numquam? Iusto veritatis possimus vitae officiis aliquam minus deleniti vero. Veritatis quas eligendi et repellat reprehenderit facere repudiandae omnis animi laboriosam voluptates ipsum excepturi optio alias provident, repellendus minima dignissimos aliquam illum eum veniam cupiditate, necessitatibus ipsa odio.</p>
        </div>
    </div>
  )
}

export default Review